language: elixir
sudo: false
elixir:
  - 1.5
  - 1.6
otp_release:
  - 19.3
  - 20.0
notifications:
  email:
    on_success: change
    on_failure: change
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix coveralls.travis

jobs:
  include:
    stage: format
    script: mix format mix.exs lib/**/*.ex test/**/*.ex test/**/*.exs --check-formatted
    elixir: 1.6
