language: elixir
sudo: false
elixir:
  - 1.3.0
  - 1.4.0
  - 1.4.2
otp_release:
  - 18.2
  - 19.3
notifications:
  email:
    on_success: change
    on_failure: change
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix coveralls.travis
